help = ('''```####### Interactive Commands #######\n
    Hey dad bot if i say ping?\n
    Hey dad bot tell me a joke\n
    Hey dad bot tell me a knock knock joke\n
    Hey dad bot how do i cook on the grill?\n
    Hey dad bot tell me a sports fact\n
    Hey dad bot tell me a fishing tip\n
    Hey dad bot insult me\n
    I love you dad bot\n
    Hi dad bot\n
    Ping me daddy!\n
```''')
pronouns = [
  'im',
  'i am',
  "i'm"
]

potty_mouth = ['Fuck you dad bot',
               'fuck you dad bot',
               'fu dad bot',
               'fu',
               'stfu dad bot',
               'Stfu dad bot',
               'STFU']

sports_facts = ["Major League Baseball umpires are required to wear black underwear while on the job in case they split their pants.",
                "Michael Jordan makes more money from Nike annually than all of the Nike factory workers in Malaysia combined.",
                "At one point in August 1971, the Pittsburgh Pirates became the first professional team to field nine players who were either black or Latino. Coincidentally, this was the same year they won the World Series.",
                "Steve Young is a great-great-great-grandson of Brigham Young of The Church of Jesus Christ of Latter-day Saints for whom Brigham Young University is named.",
                "The silhouette on the NBA logo is Hall of Fame Laker Jerry West.",
                "The referee tossed a jump ball after every basket in basketball until 1937.",
                "In July of 1934, Babe Ruth paid a fan $20 for the return of the baseball he hit for his 700th career home run.",
                "Kareem Abdul-Jabbar, the NBA's all-time leading scorer (38,387 points), collects rugs.",
                "After his jerseys were stolen from the visitors locker room when the team was on the road against the Orlando Magic, Jordan had to wear a No. 12 jersey.",
                "The average life span of an MLB baseball is five to seven pitches.",
                "Track athletes are surprisingly most likely to break records late in the day, with body temperatures at their highest.",
                "Pittsburgh is the only American city with three sports teams that wear the same colors.",
                "It takes 3,000 cows to supply the NFL with enough leather for a year’s supply of footballs.",
                "Golf balls can reach speeds of 170 miles an hour.",
                "The actual playing time in an MLB game is nine minutes and 55 seconds, despite routinely finishing at around three hours.",
                "Babe Ruth wore a cabbage leaf under his cap to keep him cool and changed it every two innings.",
                "There are more than 350 dimples on a golf ball.",
                "In 1910, an incomplete forward pass earned teams a 15-yard penalty.",
                "The household wrench was invented by boxing heavyweight champion Jack Johnson in 1922.",
                "Tug of war was an Olympic event between 1900 and 1920.",
                "Michael Jordan was once one of the best high school pitchers in North Carolina.",
                "At 120 miles per hour, a Formula One car generates so much downforce that it can drive upside down on the roof of a tunnel.",
                "A microwaved baseball will fly farther than a frozen baseball.",
                "When pitched, the average MLB baseball rotates 15 times before being hit.",
                "The state sport of Maryland is jousting.",
                "Three consecutive strikes in bowling is called a turkey.",
                "Table tennis balls can travel off the paddle at 105.6 miles per hour."
                "The original Stanley Cup was only seven-and-a-half inches high.",
                "The first baseball caps were made of straw.",
                "In the NFL, the home team must provide 36 footballs for outdoor games and 24 for indoor games.",
                "Prior to 1900, prize fights lasted up to 100 rounds.",
                "In 1935 Jesse Owens broke four world records in 45 minutes.",
                "Manute Bol's grandfather had 40 wives.",
                "People in nudist colonies play volleyball more than any other sport.",
                "No high jumper has ever been able to stay off the ground for more than one second.",
                "Most NASCAR teams use nitrogen in their tires instead of air.",
                "Hall of Fame pitcher Jim 'Catfish' Hunter garnered his nickname after Oakland Athletics owner Charles Finley made up a story that Hunter had caught a large catfish as a boy.",
                "Each year, 30,000 people are seriously injured by exercise equipment.",
                "The Los Angeles Lakers are popular in the Bahamas.",
                "Because they both lost so many players to WWII military service, the Pittsburgh Steelers and Philadelphia Eagles combined to become the Steagles during the 1943 season.",
                "At horse race tracks, the favorite wins about 30 (or less) percent of the time.",
                "A faceoff in hockey was originally called a puck-off or a face of the puck.",
                "The Kentucky Derby is the oldest continually held sports event in the United States (1875), with the second being the Westminster Kennel Club Dog show (1876).",
                "The longest running weekly rodeo in the United States, started in 1929 in (CowTown) Pilesgrove Township, New Jersey",
                "A forfeited game in baseball is recorded as 9-0.",
                "The practice of identifying baseball players by number (corresponding to a player's position in the batting order) was started by the Yankees in 1929.",
                "Left-handed people are better at sports that require good spatial judgment and fast reaction, compared to right-handed individuals.",
                "In 1986 Danny Heep became the first player in a World Series to be a designated hitter (DH) with the initials 'D.H.'",
                "Fishing is the biggest participant sport in the world.",
                "Boxing became a legal sport in 1901.",
                "More than 100 million people hold hunting licenses.",
                "Jeanne-Genevieve Garnerin was the first female parachutist, jumping from a hot air balloon in 1799.",
                "It's been said that players with brown eyes are better hitters than those with blue eyes.",
                "The record for the most Olympic medals ever won is held by Soviet gymnast Larissa Latynina. Competing in three Olympics, between 1956 and 1964, she won 18 medals.",
                "The record for the most career innings in Major League Baseball is held by Cy Young with 7,356.",
                "Kite flying is a professional sport in Thailand.",
                "In 1898, one of the first programs to be broadcast on radio was a yacht race that took place in British waters.",
                "Sports command the biggest television audiences, led by the summer Olympics, World Cup football and Formula One racing.",
                "The very first Olympic race, held in 776 BC, was won by Corubus, a chef.",
                "The first modern Olympic Games were held in Athens, Greece in 1896. There were 311 male but no female competitors.",
                "Major League Baseball teams use about 850,000 balls per season.",
                "Wrestler Kevin Nash was once the second most recruited player out of Michigan, behind none other than Magic Johnson.",
                "Basketball and rugby balls are made from synthetic material. Earlier, pigs’ bladders were used as rugby balls.",
                "Golf is the only sport played on the moon. On February 6th, 1971, Alan Shepard hit a golf ball.",
                "The only two days of the year on which there are no professional sports games (MLB, NBA, NHL or NFL) are the day before and the day after the MLB All-Star Game.",
                "Former umpire Bill Klem has the record for most games served with 5,368.",
                "About 42,000 tennis balls are used in the plus-minus 650 matches in the Wimbledon championship.",
                "The longest tennis match took place at Wimbledon 2010 when John Isner of the United States beat Nicolas Mahut of France 6-4, 3-6, 6-7 (7), 7-6 (3), 70-68 in a match that lasted 11 hours and five minutes, played over three days, June 22, 23 and 24.",
                "The 1912 Olympics was the last time that gold medals were solid gold.",
                "Former pitcher Turk Wendell used to brush his teeth and chew licorice between every inning.",
                "Basketball legend Wilt Chamberlain never fouled out of a game.",
                "If all the Super Bowl's commercials and pregame shows were strung together, their running time would be equivalent to the length of Gone with the Wind (238 minutes).",
                "Wade Boggs ate only chicken the day of a game and drew a 'Chai' (Hebrew symbol for life) in the dirt before every at-bat.",
                "In 1937, cheetahs were raced at Romford Greyhound Stadium in an effort to increase attendance (by owner Arthur Leggett).",
                "A baseball has exactly 108 stitches; a cricket ball has between 65 and 70 stitches.",
                "Before 1859, umpires sat in a padded rocking chair behind the catcher.",
                "Ari Petrof is Sweden's National Sauna Champion. He stayed in a 212-degree Fahrenheit (100-degree Celsius) sauna for five hours and 10 minutes.",
                "The Dallas Cowboys hired the NFL's first professional cheerleading squad in 1972.",
                "Deion Sanders was the first athlete to rap at a Pro Bowl musical gala in 1995.",
                "The first known combination of the words 'super' and 'bowl' dates to a third-century Chinese writer who was named Lom-Ba-Di.",
                "The first instance of global electronic communications took place in 1871 when news of the Derby winner was telegraphed from London to Calcutta in under five minutes.",
                "Billiards great Henry Lewis once sank 46 balls in a row.",
                "Mark McGwire's record-setting 70 home runs in the 1998 season traveled a total of 29,598 feet, enough to fly over Mount Everest.",
                "Australian rules football was originally designed to give cricketers something to play during the offseason.",
                "Golf was banned in England in 1457 because it was considered a distraction from the serious pursuit of archery.",
                "The oldest continuous trophy in sports is the America’s Cup. It started in 1851 with Americans winning for 132 consecutive years until Australia took the Cup in 1983.",
                "The number of chickens used to meet the nationwide demand for hot wings during the game is roughly equivalent to the population of New York City.",
                "Between two and three jockeys are killed each year. That's about how many baseball players have died in its entire professional history.",
                "Bulgaria was the only soccer team in the 1994 World Cup in which all 11 players' last names ended with the letters 'OV.'",
                "Since 1896, the beginning of the modern Olympics, only Greece and Australia have participated in every Games.",
                "Racehorses have been known to wear out new shoes in one race.",
                "Many Japanese golfers carry 'hole-in-one' insurance because it is traditional in Japan to share one's good luck by sending gifts to all your friends when you get an 'ace.' The price for what the Japanese term an 'albatross' can often reach $10,000.",
                "At 101, Larry Lewis ran the 100-yard dash in 17.8 seconds, setting a new world record for runners 100 years old or older.",
                "Honey is used as a center for golf balls.",
                "Former MLB catcher Harry Chiti was the first player ever to be traded for himself.",
                "The NFL estimates that more than 100 children are conceived every year at tailgate parties in the Super Bowl parking lot.",
                "The University of Miami had a streak of 149 consecutive regular season weeks where a former Hurricane scored a touchdown in an NFL game",
                "The yo-yo started out as a weapon in the Philippines during the 16th century before being introduced to the United States as a toy in 1929. It weighed four pounds and had a 20-foot cord.",
                "In 1963, Hall of Fame pitcher Gaylord Perry remarked, 'They'll put a man on the moon before I hit a home run.' On July 20, 1969, a few hours after Neil Armstrong set foot on the moon, Perry hit his first and only home run.",
                "NFL refs also receive Super Bowl rings.",
                "In order to take the slick factory sheen off and allow pitchers to get a better grip, Major League Baseball wipes down each baseball with mud from an undisclosed location on the Delaware River. And it’s been done this way for close to 75 years now.",
                "Two days out of 365 days of the year feature no professional sports games (MLB, NBA, NHL, or NFL). The day before and the day after the MLB All-Star Break.",
                "Japan Is Home to the World's Largest Bowling Alley. It opened in 1972 and has 116 lanes."]

knock_Jokes = ['Amos.\nAmos who?\nA mosquito bit me!',
               'Andy.\nAndy who?\nAnd he bit me again.',
               'Yetta.\nYetta who?\nYetta nother mosquito!',
               'Notta.\nNotta who?\nNotta nother mosquito!',
               'Abe Lincoln.\nAbe Lincoln who?\nAww, come on! Don’t you know who Abe Lincoln is?',
               'Lettuce.\nLettuce who?\nLettuce in and I’ll tell you!',
               'Ida\nIda who?\nIda like to be your friend!',
               'Warrior.\nWarrior who?\nWarrior been all my life!',
               'Olive.\nOlive who?\nOlive you!',
               'Adore.\nAdore who?\nAdore is between us open it up.',
               'A little boy.\nAlittle boy who?\nA little boy who can’t reach the doorbell.',
               'Anita.\nAnita who?\nAnita nother minute to think it over.',
               'Hutch.\nHutch who?\nBless you!!!',
               'Tank.\nTank who?\nYou’re welcome!',
               'Goliath.\nGoliath who?\nGoliath down, you look sleepy!!',
               'Lego.\nLego who?\nLego of me and I’ll tell you!',
               'T-Rex.\nT-Rex who?\nThere is a T-Rex at your door and you want to know his name!?!',
               'Woo.\nWoo who?\nDon’t get too excited, it’s just a joke!',
               'Police.\nPolice who?\nPol-e-s-e open the door!',
               'Nunya.\nNunya who?\nNunya business!',
               'Radio.\nRadio who?\nRadio not here I come!',
               'Howard.\nHoward who?\nHoward you like a big kiss!',
               'Issac\nIssac Who?\nIssac (I sick) of Knock Knock Jokes!',
               'Cow says.\nCow says who?\nNo, a cow says mooooo!',
               'Europe.\nEurope who?\nNo I’m not!',
               'Adore.\nAdore who?\nAdore is between us. Open up!',
               "Amish!\nAmish who?\nYou're not a shoe!",
               "Alfie\nAlfie who?\nAlfie terrible if you leave!",
               "Amish\nAmish Who?\nAw How sweet. I miss you too.",
               "Amanda\nAmanda who?\nA man da fix your sink!",
               "Al\nAl who?\nAl give you a kiss if you open this door!",
               "Avenue\nAvenue who?\nAvenue knocked on this door before?",
               "Alien\nAlien who?\nJust how many aliens do you know?",
               "Britney Spears\nBritney Spears who?\nKnock, knock - oops i did it again.",
               "Ben\nBen who?\Ben knocking on this door all morning, let me in!",
               "CD\nCD who?\nCD guy on your doorstep?",
               "Cows go\nCow's go who?\nNo, silly. Cows go Moo!",
               "Cook\nCook who?\nYes you are!",
               "Cheese\nCheese who?\nCheese a nice girl",
               "Chick!\nChick who?\nChick your oven, I can smell burning!",
               "Cupid!\nCupid who?\nCupid quiet in there.",
               "Déja.\nDéja who?\nKnock knock.",
               "Doris\nDoris who?\nThe Doris locked, why do you think I'm knocking?",
               "Dish\nDish who?\nDish is a nice place!",
               "Egg\nEgg who?\nEggstremely disappointed you still don’t recognize me.",
               "Emma\nEmma who?\nEmma bit cold out here, can you let me in?",
               "Barbie\nBarbie who?\nBarbie Q Chicken!",
               "Oswald\nOswald who?\nOswald my gum!",
               "Nuisance\nNuisance who?\nWhat’s nuisance yesterday",
               "Dwight\nDwight who?\nDwight way is better than the wrong way!",
               "Norma Lee\nNorma Lee who?\nNorma Lee I have my key, can you let me in?",
               "A little old lady\nA little old lady who?\nI didn’t know you could yodel!",
               "Dozen\nDozen who?\nDozen anybody want to let me in?",
               "Avenue\nAvenue who?\nAvenue knocked on this door before?",
               "Ice Cream\nIce Cream who?\nIce Cream if you don't let me in!",
               "Bed\nBed who?\nBed you can not guess who I am.",
               "Abby\nAbby who?\nAbby birthday to you!",
               "Rufus\nRufus who?\nRufus the most important part of your house.",
               "Wanda\nWanda who?\nWanda hang out with me right now?",
               "Ho-ho.\nHo-Ho who?\nHo-Ho You know, your Santa impression could use a little work.",
               "Mary and Abbey\nMary and Abbey who?\nMary Christmas and Abbey New Year!",
               "Carmen\nCarmen who?\nCarmen let me in already!",
               "Ya\nYa Who?\nYa I’m excited to see you too!",
               "Scold\nScold Who?\nScold outside—let me in!",
               "I'm Robin\nI'm Robin Who?\nI'm Robin you! Hand over your cash!",
               "Irish\nIrish who?\nIrish you a Merry Christmas!",
               "Otto\nOtto who?\nOtto know whats taking you so long!",
               "Needle\nNeedle who?\nNeedle little help gettin in the door.",
               "Luke\nLuke who?\nLuke through the keyhole to see!",
               "Justin\nJustin who?\nJustin the neighborhood and thought Id come over.",
               "Europe\nEurope who?\nEurope no, you are a poo",
               "To\nTo who?\nTo Whom.",
               "Etch\nEtch who?\nGod Etch You!",
               "Mikey\nMickey who?\nMickey doesnt fit through this keyhole"]

insult_list = [
    "If laughter is the best medicine, your face must be curing the world.",
    "You're so ugly, you scared the crap out of the toilet.",
    "Your family tree must be a cactus because everybody on it is a prick.",
    "No I'm not insulting you, I'm describing you.",
    "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
    "If I had a face like yours, I'd sue my parents.",
    "Your birth certificate is an apology letter from the condom factory.",
    "I guess you prove that even god makes mistakes sometimes.",
    "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
    "You're so fake, Barbie is jealous.",
    "I’m jealous of people that don’t know you!",
    "My psychiatrist told me I was crazy and I said I want a second opinion. He said okay, you're ugly too.",
    "You're so ugly, when your mom dropped you off at school she got a fine for littering.",
    "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
    "You must have been born on a highway because that's where most accidents happen.",
    "Brains aren't everything. In your case they're nothing.",
    "I don't know what makes you so stupid, but it really works.",
    "I can explain it to you, but I can’t understand it for you.",
    "Roses are red violets are blue, God made me pretty, what happened to you?",
    "Behind every fat woman there is a beautiful woman. No seriously, your in the way.",
    "Calling you an idiot would be an insult to all the stupid people.",
    "You, sir, are an oxygen thief!",
    "Some babies were dropped on their heads but you were clearly thrown at a wall.",
    "Don't like my sarcasm, well I don't like your stupid.",
    "Why don't you go play in traffic.",
    "Please shut your mouth when you’re talking to me.",
    "I'd slap you, but that would be animal abuse.",
    "They say opposites attract. I hope you meet someone who is good-looking, intelligent, and cultured.",
    "Stop trying to be a smart ass, you're just an ass.",
    "The last time I saw something like you, I flushed it.",
    "I'm busy now. Can I ignore you some other time?",
    "You have Diarrhea of the mouth; constipation of the ideas.",
    "If ugly were a crime, you'd get a life sentence.",
    "Your mind is on vacation but your mouth is working overtime.",
    "I can lose weight, but you’ll always be ugly.",
    "Why don't you slip into something more comfortable... like a coma.",
    "Shock me, say something intelligent.",
    "If your gonna be two faced, honey at least make one of them pretty.",
    "Keep rolling your eyes, perhaps you'll find a brain back there.",
    "You are not as bad as people say, you are much, much worse.",
    "I don't know what your problem is, but I'll bet it's hard to pronounce.",
    "You get ten times more girls than me? ten times zero is zero...",
    "There is no vaccine against stupidity.",
    "You're the reason the gene pool needs a lifeguard.",
    "Sure, I've seen people like you before - but I had to pay an admission.",
    "How old are you? - Wait I shouldn't ask, you can't count that high.",
    "Have you been shopping lately? They're selling lives, you should go get one.",
    "You're like Monday mornings, nobody likes you.",
    "Of course I talk like an idiot, how else would you understand me?",
    "All day I thought of you... I was at the zoo.",
    "To make you laugh on Saturday, I need to you joke on Wednesday.",
    "You're so fat, you could sell shade.",
    "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
    "Don't you need a license to be that ugly?",
    "My friend thinks he is smart. He told me an onion is the only food that makes you cry, so I threw a coconut at his face.",
    "Your house is so dirty you have to wipe your feet before you go outside.",
    "If you really spoke your mind, you'd be speechless.",
    "Stupidity is not a crime so you are free to go.",
    "You are so old, when you were a kid rainbows were black and white.",
    "If I told you that I have a piece of dirt in my eye, would you move?",
    "You so dumb, you think Cheerios are doughnut seeds.",
    "So, a thought crossed your mind? Must have been a long and lonely journey.",
    "You are so old, your birth-certificate expired.",
    "Every time I'm next to you, I get a fierce desire to be alone.",
    "You're so dumb that you got hit by a parked car.",
    "Keep talking, someday you'll say something intelligent!",
    "You're so fat, you leave footprints in concrete.",
    "How did you get here? Did someone leave your cage open?",
    "Pardon me, but you've obviously mistaken me for someone who gives a damn.",
    "Wipe your mouth, there's still a tiny bit of bullshit around your lips.",
    "Don't you have a terribly empty feeling - in your skull?",
    "As an outsider, what do you think of the human race?",
    "Just because you have one doesn't mean you have to act like one.",
    "We can always tell when you are lying. Your lips move.",
    "Are you always this stupid or is today a special occasion?",
    "The best part of you slid down the crack of your mom's ass.",
    "your mom should have swallowed you."]


grillMaster_Tips = ["Always keep the grill clean",
                    "Oil the Food, Not the Grate",
                    "Preheat your grill with the lid closed for 10 to 15 minutes.",
                    "With all the coals glowing red, or all the gas burners on high, the temperature under the lid should reach 500F.",
                    "Preheating your grill helps prevent food from sticking to the grate, and gets the grate hot enough to sear properly.",
                    "When bits of food have stuck to your cooking grate, and the grate is hot, clean it with a stainless steel brush. This step is not only for cleanliness. It also prevents your food from sticking.",
                    "Oil prevents food from sticking. It adds flavor and moisture, too.",
                    "Lightly brushing or spraying the food with oil works better than brushing the grate.",
                    "Keeping the Grill Lid closed keeps the grates hot enough to sear the food.",
                    "Keeping the Grill Lid closed speeds up the cooking time and prevents the food from drying out.",
                    "Keeping the Grill Lid closed traps the smokiness that develops when fat and juices vaporize in the grill.",
                    "Keeping the Grill Lid closed prevents flare-ups by limiting oxygen.",
                    "By monitoring your time and temperature you avoid overcooking your food.",
                    "You should always use a timer.",
                    "If you are grilling in a colder climate or in a higher altitude, the cooking times will be longer. If the wind is blowing hard, it will lower a gas grill's temperature and raise a charcoal grill's temperature.",
                    "Direct heat (when the fire is directly below the food) is best for relatively small, tender pieces of food that cook in 20 minutes or less.",
                    "Indirect heat (when the fire is on either side of the food) is best for larger, tougher cuts of meat that require more than 20 minutes of cooking.",
                    "The dampers on the top and bottom of the grill control the airflow inside the grill. The more air flowing into the grill, the hotter the fire will grow and the more frequently you will have to replenish it. To slow the rate of your fuel burning, close the top vent as much as halfway and keep the lid on as much as possible. The bottom vent should be left open whenever you are grilling so you don’t kill your fire.",
                    "Under normal circumstances, a typical charcoal briquette fire will lose about 100˚F of heat over 40 to 60 minutes. A typical lump charcoal fire will lose heat even faster.",
                    "Gas grills have individual control knobs so that you can easily regulate the heat and create different grilling zones easily. You can easily maintain heat levels as low as 200˚F to over 550˚F easily and shift from direct to indirect in minutes.",
                    "If you do choose charcoal grilling, I recommend additive-free lump charcoal, which is just charred wood.",
                    "It's easier to remove debris when the grill is hot, so after preheating, use a long-handled wire grill brush on your grill rack to clean off charred debris from prior meals. Scrape again immediately after use.",
                    "The trick to smoking is that you don't want the fire too hot, because it will burn the meat",
                    "To give your burger that classic, round look, create a indent in the center with the back of a spoon while you're making the patty. The meat will rise in the middle of the burger as it cooks, puffing it up to perfection.",
                    "To prevent your bamboo or wooden skewers from burning, soak them in warm water for 30 minutes to an hour before you place them on a hot grill.",
                    "Thread two skewers (or use a two-prong skewer) through each kebab to avoid the food from moving around as you flip the kebab.",
                    "If you love grilling corn, tofu or fruit, a grilling basket is a worthy investment. A basket keeps the food safe from falling through the rack, and it doesn't take away from the flavor.",
                    "When grilling, lay food on the grate in orderly lines, moving from left to right. Or for quick-cooking items, such as shrimp and scallops, arrange in a circle going clockwise. This will help you keep track of which foods hit the flames first, and also allow you to group raw items away from cooked ones.",
                    "When checking for doneness, resist the urge to repeatedly poke, stab, or flip your food. Instead, give food time to sear and develop a crust; turn only when grill marks form.",
                    "Food continues to cook after it comes off the grill, so it's best to remove it just before it has reached the desired doneness.",
                    "Don't over do it when it comes to cooking meat. You can always place the meat back on the grill if it's slightly underdone, but you can't go back if it's overcooked",
                    "Let food rest before serving—a few minutes for small cuts, up to 15 minutes for roasts.",
                    "Keep a spray bottle filled with water handy; this will allow you to dampen flare-ups without interfering with heat.",
                    "If it’s soft like the flesh between your index finger and thumb, it’s rare. If it’s soft like your cheek, it’s medium-rare, and if it’s firm like your forehead it’s well-done.",
                    "Buy from a good butcher shop or from the butcher at your supermarket's meat counter. Avoid prepackaged steaks—plastic wrap traps in moisture.",
                    "Spring for USDA Prime or Certified Black Angus steaks if you can. Choice-grade steak is a good, less-expensive alternative.",
                    "Thin white streaks of fat throughout a steak, called marbling, keep the meat nice and juicy. Plus, the fat adds flavor.",
                    "Take your steak out of the fridge about 20 minutes before grilling to bring it to room temperature. A freezing-cold steak won't cook evenly.",
                    "You don't need elaborate equipment to make a tasty steak—just a solid pair of tongs, a brush and a grill.",
                    "Let your steak develop a seared crust on the grill before moving or flipping it. If you try to lift the meat before it's ready, it'll stick to the grates.",
                    "Once your steak is off the grill, wait at least 5 minutes before slicing. This gives the juices a chance to settle back into the meat."]

fishing_Tips = ["When your plastic worms get torn up, save ’em. Bass like to ambush wounded prey, so a beat-up worm is perfect to use, especially in shallow water.",
                "In shallow cover—wood, stumps, clumps of grass—I like to use a spinner bait with a red or pink head, and a crank bait with red hooks. The red makes the fish think the bait’s injured, and they’ll bite at it.",
                "When you cast, stop halfway instead of following through, similar to a check swing in baseball. This makes the lure hit the surface of the water a few feet before your target, so the lure skitters over the water. It’s a good way to get under docks and other structures.",
                "I use a file to sharpen my hooks every time I catch a fish and before every trip. It takes 30 seconds. Bass have boney jaws, so a sharp hook is more apt to penetrate the fish.",
                "When you put a bass in the livewell, they’re notorious for spitting up what they were feeding on. From there you can tell what color lure or kind of lure to throw the rest of the day.",
                "Sacrifice some distance in your casts and fish with the wind in your face. Bass always swim with the current, so it’s better for them to find your bait before they find your boat. Plus, the noise of water slapping your hull will carry away from the spot you’re fishing, which is good.",
                "In the spring bass hang out in spawning beds. Concentrate on shallow areas, especially in pockets and coves protected from the wind because this is where they like to guard their eggs. They’ll bite as much out of irritation with the lure as they will out of hunger.",
                "Bass eat different bait depending on the time of year. The general rule is early in the year they like crawfish, so use peach-colored patterns. In the summer and fall they like shad, so use chrome or silver baits.",
                "The best time to fish bass is before a front comes through, and the worst time to fish them is after. The pressure makes the bass more active, so watch for a wall of clouds moving in. When it’s too pretty out, bass aren’t likely to bite.",
                "The best time to fish bass is before a front comes through, and the worst time to fish them is after. The pressure makes the bass more active, so watch for a wall of clouds moving in. When it’s too pretty out, bass aren’t likely to bite.",
                "Bass is an ornery fish. You have to keep tapping at it to upset it into biting your hook. Bass position themselves in cover, and like the lure presented to them at different angles. I’ve tossed lures a hundred times onto the same location until finally getting a bite.",
                "A plastic worm that has been torn or cut in half can be stuck together very easily. Heat the two ends over a lighter till they melt, then hold them together while the plastic hardens. The “weld” will be as strong as the original worm.",
                "You can brighten tarnished spoon and spinner blades, or paint a glittery body on a streamer fly hook, with an “ultra-iridescent” sparkling fingernail polish. It can be found in copper and silver colors in a small bottle with a brush applicator, and costs only two bits.",
                "When you find line-grooves in a rod guide, usually at the tip top, you can buff them away with thin strips of emery cloth. But this leaves a rough surface, so always finish the job by polishing the inside of the guides with crocus cloth (jeweler’s rouge).",
                "When you return home after a day of fishing, make it a habit to leave your box of lures or book of flies open overnight so the contents can dry out. Moisture trapped in an airtight container will soon rust hooks and tarnish metal lures.",
                "When you run your boat ashore after a day’s fishing, stop the motor by disconnecting the fuel line and letting the motor idle till the carburetor runs dry. This will eliminate the chance that fuel may leak out when you put the kicker in the car trunk.",
                "A frozen fish should be thawed slowly. Either put it in the refrigerator 24 hours before cooking it or place it in cold water. If the fish is thawed too fast, the outside flesh may deteriorate while the inside is still frozen too hard to cook through.",
                "To provide a contrasty background for tying flies, paint the tying table soft white or another light shade, or use self-adhering, shelf-lining material in a solid color (light green is ideal). It’s easier on the eyes when tying very small flies.",
                "As a rule of thumb, fish should not be kept in the refrigerator longer than two days before being cooked, for they lose their flavor rapidly. If it is necessary to keep the fish any longer than two days, it is better to quick-freeze them instead.",
                "Two tips for keeping rod ferrules from sticking: One, don’t lubricate them, because oil or nose grease collects dust and dirt. Keep both ferrules dry and clean. Two, take the rod apart as soon as you quit fishing so the metal can’t oxidize and lock.",
                "Small leaks and briar-pricks in boots or waders can be plugged temporarily by melting the end of a plastic worm and smearing the hot goo over the hole. The plastic hardens in a few seconds and sticks well.",
                "Of the many ways to prevent the mesh of a landing net from becoming entangled in brush, twigs, and barbed wire fences, this is the simplest: Slip a heavy rubber band over the handle of the net and tuck the tip-end of the net bag under it.",
                "When fishing high, cold water in the early spring with spinning gear, try casting diagonally upstream and retrieving just fast enough to keep the lure from hanging on bottom. This often takes sluggish trout that refuse to budge for anything else.",
                "October is the time when bass start to move out into their winter quarters. The larger ones, especially, seek out the deeper holes. One way to locate them is to scratch bottom in from 10 to 20 feet of water with a plastic worm fished very slowly.",
                "Saturday morning fishing trips with Dad are as iconic as ballgames and crackerjacks.",
                "Learn how to cast a spinning rod and a bait caster accurately – most times you'll need to put the bait with in a few feet of the strike zone where a poor casting results in missed opportunities and also lost lures.",
                "When using plastic baits like worms, Senkos or craws, don’t jerk - I see this happen all the time, beginning anglers have a hard time distinguishing between a bite and a snag resulting in the bait moved from the strike zone.",
                "The best way to determine a bite is to hold the rod steady with a little tension and see if there is a pulsation, if so then jerk. When using plastics bass will usually hold on to the bait for a couple seconds – enough time to figure if it’s a fish or a snag.",
                "When using a new lure it will take some time to get the hang of it and develop confidence in it. A good way to do this is to go fishing with only that lure. This forces you to use that bait and learn how to work it to catch fish.",
                "For new fishermen that want to get out on the water but don't have a boat, try kayak fishing. Kayaks are affordable, light weight, and easy to transport. They also allow you to get in those spots not accessible by foot or power boats that often hold some of the biggest, un-pressured fish!",
                " Aside from obviously needing a rod and reel, other things that you will eventually need would be a tackle box, needle- nose pliers, a net, and perhaps an ice chest. Also a nice pair of polarized sunglasses will not only block the UV rays from the sun and the sun's glare on the water, but they will help you to see a little better into the water to locate fish. "]

son_Names = ['Chief',
            "Sport",
            "Champ",
            "Slugger",
            "Kiddo",
            "Squirt",
            "Little Buddy",
            "Tigger",
            "Pal",
            "Buckaroo",
            "Buddy",
            "Dude",
            "Cowboy",
            "Little Dude",
            "Little Guy",
            "Youngster",
            "Bucko",
            "Bub",
            "Boss",
            "Fella",
            "Killer",
            "Big Guy",
            "Toughguy"]

activities =["with other dad's",
             "Catch",
             "with fishing hooks",
             "With the grill",
             "Golf"]

love_response = ["I know.",
                      "No",
                      "......",
                      "did someone say something?",
                      "Well....This is a bit awkward but do i know you?",
                      "Who the hell are you?",
                      "Huh?",
                      "Who the hell let you out of the house?",
                      "Do i know you?",
                      "Wrong dad bot kid",
                      "..... Who said you could talk jr?"]
